version: 2
jobs:
  test8:
    working_directory: ~/leiningen
    docker:
      - image: clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run:
          working_directory: ~/leiningen/leiningen-core
          command: lein bootstrap
      - run: bin/lein test
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
            - $HOME/leiningen/leiningen-core/.lein-bootstrap
          key: << checksum "project.clj" >>

  test11:
    working_directory: ~/leiningen
    docker:
      - image: openjdk:11-ea-jdk
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: bin/lein test

workflows:
  version: 2
  test:
    jobs:
      - test8
      - test11:
          requires: # this needs the bootstrapped classpath from test8
            - test8
